# Generated by Django 5.2.17 on 2026-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliowork',
            name='legacy_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
