# Generated by Django 5.2.17 on 2026-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('studio', '0002_alter_enquiry_legacy_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='studio_role_privileges_valid',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_staff', True), ('role', 'ADMIN')), models.Q(('is_staff', False), ('is_superuser', False), ('role', 'CLIENT')), _connector='OR'), name='studio_role_privileges_valid'),
        ),
    ]
